apiVersion: v1
kind: Service
metadata:
  name: appservice
  labels:
    app: my-app
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: http

  # Note here that we match both the app and the version
  selector:
    version: v1.0.0
    app: my-app
